export default {
  VIDEO_SERVICE: process.env.REACT_APP_VIDEO_SERVICE,
  VIDEO_HISTORY_SERVICE: process.env.REACT_APP_VIDEO_HISTORY_SERVICE,
  MATERIAL_SERVICE: process.env.REACT_APP_MATERIAL_SERVICE,
  SUBJECT_SERVICE: process.env.REACT_APP_SUBJECT_SERVICE,
  AUTHENTICATION_SERVICE: process.env.REACT_APP_AUTHENTICATION_SERVICE,
  FRONTEND_SERVICE: process.env.REACT_APP_FRONTEND_SERVICE,
}